# Generated by Django 3.1.2 on 2020-10-05 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('abrv', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courseID', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='schedule.department')),
            ],
            options={
                'unique_together': {('department', 'courseID')},
            },
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('courses', models.ManyToManyField(to='schedule.Course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='schedule.department')),
            ],
            options={
                'unique_together': {('department', 'year')},
            },
        ),
    ]
