# Generated by Django 3.1.2 on 2020-10-14 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=6)),
                ('year', models.IntegerField()),
                ('techUnits', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courseID', models.TextField()),
                ('numUnits', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('abrv', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GEArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('C1', 'C1'), ('C2', 'C2'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('E', 'E'), ('R', 'R'), ('S', 'S'), ('V', 'V'), ('Z', 'Z')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='GERequirement',
            fields=[
                ('reqID', models.AutoField(primary_key=True, serialize=False)),
                ('numCourses', models.IntegerField()),
                ('GEAreas', models.ManyToManyField(to='schedule.GEArea')),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('WSTPassed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransferCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courseID', models.CharField(max_length=30)),
                ('numUnits', models.IntegerField(default=3)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='schedule.college')),
            ],
            options={
                'unique_together': {('school', 'courseID')},
            },
        ),
        migrations.CreateModel(
            name='TransferGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F')], default='F', max_length=2)),
                ('courseType', models.CharField(choices=[('General', 'General'), ('GE', 'GE'), ('Lower Div', 'Lower Div'), ('Upper Div', 'Upper Div'), ('Tech Elective', 'Tech Elective')], default='General', max_length=13)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='schedule.transfercourse')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.transcript')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F')], default='F', max_length=2)),
                ('courseType', models.CharField(choices=[('General', 'General'), ('GE', 'GE'), ('Lower Div', 'Lower Div'), ('Upper Div', 'Upper Div'), ('Tech Elective', 'Tech Elective')], default='General', max_length=13)),
                ('GEReqID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.gerequirement')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='schedule.course')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.transcript')),
            ],
        ),
        migrations.AddField(
            model_name='transcript',
            name='coursesTaken',
            field=models.ManyToManyField(through='schedule.TranscriptGrade', to='schedule.Course'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='coursesTransfered',
            field=models.ManyToManyField(through='schedule.TransferGrade', to='schedule.TransferCourse'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='schedule.catalogue')),
                ('friendRequests', models.ManyToManyField(related_name='RequestFriends', to='schedule.Student')),
                ('friends', models.ManyToManyField(related_name='_student_friends_+', to='schedule.Student')),
                ('roadmap', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.roadmap')),
                ('transcript', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.transcript')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=6)),
                ('year', models.IntegerField()),
                ('courses', models.ManyToManyField(to='schedule.Course')),
                ('transferCourses', models.ManyToManyField(to='schedule.TransferCourse')),
            ],
        ),
        migrations.AddField(
            model_name='roadmap',
            name='semesterSchedules',
            field=models.ManyToManyField(to='schedule.SemesterSchedule'),
        ),
        migrations.CreateModel(
            name='PrereqGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F')], default='C', max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='The_Course', to='schedule.course')),
                ('prereq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='The_Prereq', to='schedule.course')),
            ],
            options={
                'unique_together': {('course', 'prereq')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='GEArea',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.gearea'),
        ),
        migrations.AddField(
            model_name='course',
            name='coreqs',
            field=models.ManyToManyField(blank=True, related_name='Corequisites', to='schedule.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='schedule.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(blank=True, related_name='Prerequisites', through='schedule.PrereqGrade', to='schedule.Course'),
        ),
        migrations.CreateModel(
            name='CatalogueGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F')], default='C-', max_length=2)),
                ('GEReqID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.gerequirement')),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.catalogue')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.course')),
            ],
        ),
        migrations.AddField(
            model_name='catalogue',
            name='GEReqs',
            field=models.ManyToManyField(to='schedule.GERequirement'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='courses',
            field=models.ManyToManyField(through='schedule.CatalogueGrade', to='schedule.Course'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='schedule.department'),
        ),
        migrations.CreateModel(
            name='TechElective',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.department')),
            ],
            options={
                'unique_together': {('department', 'course')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'courseID')},
        ),
        migrations.AlterUniqueTogether(
            name='catalogue',
            unique_together={('department', 'year', 'term')},
        ),
        migrations.CreateModel(
            name='Articulation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SJSUCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.course')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.transfercourse')),
            ],
            options={
                'unique_together': {('course', 'SJSUCourse')},
            },
        ),
    ]
