# Generated by Django 3.1.2 on 2020-10-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_catalogue_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coreqs',
            field=models.ManyToManyField(blank=True, related_name='_course_coreqs_+', to='schedule.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(blank=True, to='schedule.Course'),
        ),
    ]
