# Generated by Django 3.1.2 on 2020-10-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20201014_0451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('department', 'courseID')},
        ),
        migrations.RemoveField(
            model_name='course',
            name='GEArea',
        ),
        migrations.AddField(
            model_name='course',
            name='GEArea',
            field=models.ManyToManyField(to='schedule.GEArea'),
        ),
    ]
