# Generated by Django 3.1.2 on 2020-10-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20201017_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='GEArea',
            field=models.ManyToManyField(blank=True, to='schedule.GEArea'),
        ),
    ]
