# Generated by Django 3.1.2 on 2020-10-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20201005_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coreqs',
            field=models.ManyToManyField(blank=True, related_name='Corequisites', to='schedule.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(blank=True, related_name='Prerequisites', to='schedule.Course'),
        ),
    ]
