# Generated by Django 3.1.2 on 2020-10-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20201017_0439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulation',
            options={'ordering': ('course', 'SJSUCourse')},
        ),
        migrations.AlterModelOptions(
            name='catalogue',
            options={'ordering': ('department', 'year', 'term')},
        ),
        migrations.AlterModelOptions(
            name='cataloguegrade',
            options={'ordering': ('catalogue', 'course')},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('studentID',)},
        ),
        migrations.AlterModelOptions(
            name='techelective',
            options={'ordering': ('department', 'course')},
        ),
        migrations.AlterModelOptions(
            name='transcriptgrade',
            options={'ordering': ('transcript', 'course')},
        ),
        migrations.AlterModelOptions(
            name='transfercourse',
            options={'ordering': ('school', 'courseID')},
        ),
        migrations.AlterModelOptions(
            name='transfergrade',
            options={'ordering': ('transcript', 'course')},
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='semesterSchedules',
            field=models.ManyToManyField(related_name='From_Roadmap', to='schedule.SemesterSchedule'),
        ),
        migrations.AlterUniqueTogether(
            name='cataloguegrade',
            unique_together={('course', 'catalogue')},
        ),
        migrations.AlterUniqueTogether(
            name='transcriptgrade',
            unique_together={('course', 'transcript')},
        ),
        migrations.AlterUniqueTogether(
            name='transfergrade',
            unique_together={('course', 'transcript')},
        ),
    ]
