# Generated by Django 3.1.2 on 2020-10-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20201019_0802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('abrv',)},
        ),
        migrations.AlterModelOptions(
            name='gearea',
            options={'ordering': ('area',)},
        ),
        migrations.AlterModelOptions(
            name='prereqgrade',
            options={'ordering': ('course', 'prereq')},
        ),
        migrations.RemoveField(
            model_name='cataloguegrade',
            name='GEReqID',
        ),
        migrations.AddField(
            model_name='cataloguegrade',
            name='GEReqID',
            field=models.ManyToManyField(blank=True, to='schedule.GERequirement'),
        ),
        migrations.RemoveField(
            model_name='transcriptgrade',
            name='GEReqID',
        ),
        migrations.AddField(
            model_name='transcriptgrade',
            name='GEReqID',
            field=models.ManyToManyField(blank=True, to='schedule.GERequirement'),
        ),
    ]
