# Generated by Django 3.1.2 on 2020-10-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20201021_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerequirement',
            name='numCourses',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='gerequirement',
            name='numUnits',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
