# Generated by Django 3.1.2 on 2020-10-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20201021_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='perferredCourses',
            field=models.ManyToManyField(to='schedule.Course'),
        ),
    ]
