# Generated by Django 3.1.2 on 2020-10-22 04:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0011_student_perferredcourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='numYears',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='student',
            name='startDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
