# Generated by Django 3.1.2 on 2020-10-24 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20201022_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='perferredCourses',
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='GEReqs',
            field=models.ManyToManyField(blank=True, to='schedule.GERequirement'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='courses',
            field=models.ManyToManyField(blank=True, through='schedule.CatalogueGrade', to='schedule.Course'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='semesterSchedules',
            field=models.ManyToManyField(blank=True, related_name='From_Roadmap', to='schedule.SemesterSchedule'),
        ),
        migrations.AlterField(
            model_name='semesterschedule',
            name='courses',
            field=models.ManyToManyField(blank=True, to='schedule.Course'),
        ),
        migrations.AlterField(
            model_name='semesterschedule',
            name='transferCourses',
            field=models.ManyToManyField(blank=True, to='schedule.TransferCourse'),
        ),
        migrations.AlterField(
            model_name='student',
            name='friendRequests',
            field=models.ManyToManyField(blank=True, related_name='RequestFriends', to='schedule.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_student_friends_+', to='schedule.Student'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='coursesTaken',
            field=models.ManyToManyField(blank=True, through='schedule.TranscriptGrade', to='schedule.Course'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='coursesTransfered',
            field=models.ManyToManyField(blank=True, through='schedule.TransferGrade', to='schedule.TransferCourse'),
        ),
        migrations.CreateModel(
            name='PreferredCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.course')),
                ('reqID', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.gerequirement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.student')),
            ],
            options={
                'ordering': ('student', 'course'),
            },
        ),
        migrations.AddField(
            model_name='student',
            name='prefCourseList',
            field=models.ManyToManyField(blank=True, through='schedule.PreferredCourse', to='schedule.Course'),
        ),
    ]
