# Generated by Django 3.1.2 on 2020-10-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20201024_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferredcourse',
            name='courseType',
            field=models.CharField(choices=[('General', 'General'), ('GE', 'GE'), ('Lower Div', 'Lower Div'), ('Upper Div', 'Upper Div'), ('Tech Elective', 'Tech Elective')], default='General', max_length=13),
        ),
    ]
