# Generated by Django 3.1.2 on 2020-10-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_preferredcourse_coursetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isCapstone',
            field=models.BooleanField(default=False),
        ),
    ]
