# Generated by Django 3.1.2 on 2020-11-05 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_course_iscapstone'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='NCoreqs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='NOfCoreqs',
            field=models.ManyToManyField(blank=True, related_name='Optional_Corequisites', to='schedule.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='NPrereqs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='unitPrereq',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prereqgrade',
            name='grade',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F')], default='C-', max_length=2),
        ),
        migrations.CreateModel(
            name='OptionalPrereqGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F')], default='C-', max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='The_Optional_Course', to='schedule.course')),
                ('prereq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='The_Optional_Prereq', to='schedule.course')),
            ],
            options={
                'ordering': ('course', 'prereq'),
                'unique_together': {('course', 'prereq')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='NOfPrereqs',
            field=models.ManyToManyField(blank=True, related_name='Optional_Prerequisites', through='schedule.OptionalPrereqGrade', to='schedule.Course'),
        ),
    ]
