# Generated by Django 3.1.2 on 2020-11-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_auto_20201105_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='requiresWST',
            field=models.BooleanField(default=False),
        ),
    ]
