# Generated by Django 3.1.2 on 2020-11-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_course_requireswst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='startDate',
        ),
        migrations.AddField(
            model_name='course',
            name='GEPrereqs',
            field=models.ManyToManyField(blank=True, related_name='GE_Prerequisites', to='schedule.GEArea'),
        ),
        migrations.AddField(
            model_name='student',
            name='startTerm',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], default='Fall', max_length=6),
        ),
        migrations.AddField(
            model_name='student',
            name='startYear',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='course',
            name='GEArea',
            field=models.ManyToManyField(blank=True, related_name='GE_Areas', to='schedule.GEArea'),
        ),
    ]
