# Generated by Django 3.1.2 on 2020-11-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_auto_20201115_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='separateSV',
            field=models.BooleanField(default=False),
        ),
    ]
