# Generated by Django 3.1.2 on 2020-11-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_student_separatesv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='numYears',
        ),
        migrations.AddField(
            model_name='course',
            name='isAlternateCapstone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='currentTerm',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], default='Fall', max_length=6),
        ),
        migrations.AddField(
            model_name='student',
            name='currentYear',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='student',
            name='numSemesters',
            field=models.IntegerField(default=8),
        ),
    ]
