# Generated by Django 3.1.2 on 2020-11-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_auto_20201116_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.IntegerField(null=True),
        ),
    ]
