# Generated by Django 3.1.2 on 2020-11-16 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_auto_20201116_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='friendRequests',
            field=models.ManyToManyField(blank=True, related_name='RequestFriends', to='schedule.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_student_friends_+', to='schedule.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.CreateModel(
            name='PreferredCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseType', models.CharField(choices=[('General', 'General'), ('GE', 'GE'), ('Lower Div', 'Lower Div'), ('Upper Div', 'Upper Div'), ('Tech Elective', 'Tech Elective')], default='General', max_length=13)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.course')),
                ('reqID', models.ManyToManyField(blank=True, default=None, to='schedule.GERequirement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.student')),
            ],
            options={
                'ordering': ('student', 'course'),
            },
        ),
        migrations.AddField(
            model_name='student',
            name='prefCourseList',
            field=models.ManyToManyField(blank=True, through='schedule.PreferredCourse', to='schedule.Course'),
        ),
    ]
