# Generated by Django 3.1.2 on 2020-11-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_auto_20201116_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sequential',
            field=models.ManyToManyField(blank=True, related_name='Sequential', to='schedule.Course'),
        ),
    ]
